# Generated by Django 5.0.3 on 2024-03-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authtable',
            table='AuthTable',
        ),
    ]
