# Generated by Django 5.0.3 on 2024-03-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_authtable_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthTable',
        ),
    ]
