# Generated by Django 5.0.3 on 2024-04-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
